[package]
name = "cryptocontent"
version = "0.1.0"
authors = ["malet <malet@gmx.at>"]

[dependencies]
uuid  = "0.1"
rustc-serialize = "0.3.15"
sodiumoxide = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]
