[package]
name = "cryptocontent"
version = "0.1.0"
authors = ["malet <malet@gmx.at>"]

[dependencies]
uuid  = "*"
rustc-serialize = "*"
sodiumoxide = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]
