[package]
name = "cryptocontent"
version = "0.1.0"
authors = ["malet <malet@gmx.at>"]

[dependencies]
uuid  = "0.1.18"
sodiumoxide = "0.0.9"
rustc-serialize = "*"

[dependencies.chrono]
version = "0.2.17"
features = ["rustc-serialize"]
