[package]
name = "cryptocontent"
version = "0.1.0"
authors = ["malet <malet@gmx.at>"]

[dependencies]
uuid  = "*"
sodiumoxide = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]
